# SPDX-License-Identifier: GPL-3.0-or-later
import os
import re
import subprocess
import sys
import tempfile

VCVARS = r"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
SYSTEM_DXGI = r"C:\Windows\System32\dxgi.dll"

def dump_exports(dll):
    """Run dumpbin via a temp .bat — passing 'call vcvars && dumpbin "..."' as a
    subprocess list mangles the embedded quotes and dumpbin exits silently."""
    fd, bat = tempfile.mkstemp(suffix=".bat")
    os.close(fd)
    try:
        with open(bat, "w", encoding="utf-8") as fh:
            fh.write(f'@echo off\ncall "{VCVARS}" >nul 2>&1\ndumpbin /nologo /exports "{dll}"\n')
        out = subprocess.run([bat], capture_output=True, text=True, timeout=120)
        if out.returncode != 0 or "exports" not in out.stdout:
            raise SystemExit(f"dumpbin failed (rc={out.returncode})\n{out.stdout}\n{out.stderr}")
        return out.stdout
    finally:
        try:
            os.remove(bat)
        except OSError:
            pass

def parse(text):
    exports = []
    for line in text.splitlines():
        m = re.match(r"\s*(\d+)\s+[0-9A-Fa-f]+\s+[0-9A-Fa-f]{8}\s+(\S+)\s*$", line)
        if m:
            exports.append((int(m.group(1)), m.group(2)))
    return sorted(exports)

def write_asm(path, names):

    L = ["; generated by gen_def.py - do not edit",
         "; Each export jmps through a runtime-resolved pointer to the genuine",
         "; System32 dxgi.dll (see real_ptrs.c). No import library, no dxgi_real.dll.",
         ""]
    L += [f"EXTERN real_{n}:QWORD" for n in names]
    L += ["", ".code", ""]
    for name in names:
        # thunk_ prefix keeps the symbol distinct from the export name; exports.def
        # aliases the real export name back to thunk_<name>.
        L += [f"thunk_{name} PROC",
              f"    jmp QWORD PTR [real_{name}]",
              f"thunk_{name} ENDP", ""]
    L.append("END")
    with open(path, "w", encoding="ascii") as fh:
        fh.write("\n".join(L) + "\n")

def write_real_ptrs_c(path, names):
    """The function pointers the thunks jmp through, plus a resolver that fills them
    from the real System32 dxgi.dll. Replaces the old static import on dxgi_real.dll,
    so the proxy is a single self-contained DLL."""
    L = ["/* generated by gen_def.py - do not edit */",
         "#include <windows.h>",
         "/* function<->data pointer cast is a documented, safe MSVC extension here */",
         "#pragma warning(disable:4152)",
         ""]
    L += [f"void *real_{n};" for n in names]
    L += ["",
          "/* Returns the count of exports that could NOT be resolved (0 = all good). */",
          "int acre_resolve_real(HMODULE h) {",
          "    int missing = 0;"]
    for n in names:
        L.append(f'    real_{n} = (void *)GetProcAddress(h, "{n}"); if (!real_{n}) missing++;')
    L += ["    return missing;",
          "}"]
    with open(path, "w", encoding="ascii") as fh:
        fh.write("\n".join(L) + "\n")

def write_def(path, names):
    """Export each real DXGI name, aliased to our thunk_ symbol. Aliasing to a local
    symbol is well-supported; it's only `name=other_module.name` forwarding that MSVC
    refuses once an object file is in the link."""
    L = ["; generated by gen_def.py - do not edit", "EXPORTS"]
    L += [f"    {n}=thunk_{n}" for n in names]
    with open(path, "w", encoding="ascii") as fh:
        fh.write("\n".join(L) + "\n")

def write_header(path, names):
    L = ["/* generated by gen_def.py - do not edit */",
         "#pragma once",
         f"#define DXGI_EXPORT_COUNT {len(names)}",
         "static const char *const kDxgiExportNames[DXGI_EXPORT_COUNT] = {"]
    L += [f'    "{n}",' for n in names]
    L += ["};"]
    with open(path, "w", encoding="ascii") as fh:
        fh.write("\n".join(L) + "\n")

def main():
    here = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.abspath(__file__))
    exports = parse(dump_exports(SYSTEM_DXGI))
    if len(exports) < 10:
        raise SystemExit(f"only parsed {len(exports)} exports — dumpbin format changed?")
    names = [n for _o, n in exports]
    write_asm(os.path.join(here, "thunks.asm"), names)
    write_def(os.path.join(here, "exports.def"), names)
    write_real_ptrs_c(os.path.join(here, "real_ptrs.c"), names)
    write_header(os.path.join(here, "dxgi_names.h"), names)
    print(f"generated thunks.asm / exports.def / real_ptrs.c / dxgi_names.h "
          f"for {len(names)} exports")
    for i, n in enumerate(names):
        print(f"  [{i:2}] {n}")

if __name__ == "__main__":
    main()
