/* generated by gen_def.py - do not edit */
#include <windows.h>
/* function<->data pointer cast is a documented, safe MSVC extension here */
#pragma warning(disable:4152)

void *real_ApplyCompatResolutionQuirking;
void *real_CompatString;
void *real_CompatValue;
void *real_DXGIDumpJournal;
void *real_PIXBeginCapture;
void *real_PIXEndCapture;
void *real_PIXGetCaptureState;
void *real_SetAppCompatStringPointer;
void *real_UpdateHMDEmulationStatus;
void *real_CreateDXGIFactory;
void *real_CreateDXGIFactory1;
void *real_CreateDXGIFactory2;
void *real_DXGID3D10CreateDevice;
void *real_DXGID3D10CreateLayeredDevice;
void *real_DXGID3D10GetLayeredDeviceSize;
void *real_DXGID3D10RegisterLayers;
void *real_DXGIDeclareAdapterRemovalSupport;
void *real_DXGIDisableVBlankVirtualization;
void *real_DXGIGetDebugInterface1;
void *real_DXGIReportAdapterConfiguration;

/* Returns the count of exports that could NOT be resolved (0 = all good). */
int acre_resolve_real(HMODULE h) {
    int missing = 0;
    real_ApplyCompatResolutionQuirking = (void *)GetProcAddress(h, "ApplyCompatResolutionQuirking"); if (!real_ApplyCompatResolutionQuirking) missing++;
    real_CompatString = (void *)GetProcAddress(h, "CompatString"); if (!real_CompatString) missing++;
    real_CompatValue = (void *)GetProcAddress(h, "CompatValue"); if (!real_CompatValue) missing++;
    real_DXGIDumpJournal = (void *)GetProcAddress(h, "DXGIDumpJournal"); if (!real_DXGIDumpJournal) missing++;
    real_PIXBeginCapture = (void *)GetProcAddress(h, "PIXBeginCapture"); if (!real_PIXBeginCapture) missing++;
    real_PIXEndCapture = (void *)GetProcAddress(h, "PIXEndCapture"); if (!real_PIXEndCapture) missing++;
    real_PIXGetCaptureState = (void *)GetProcAddress(h, "PIXGetCaptureState"); if (!real_PIXGetCaptureState) missing++;
    real_SetAppCompatStringPointer = (void *)GetProcAddress(h, "SetAppCompatStringPointer"); if (!real_SetAppCompatStringPointer) missing++;
    real_UpdateHMDEmulationStatus = (void *)GetProcAddress(h, "UpdateHMDEmulationStatus"); if (!real_UpdateHMDEmulationStatus) missing++;
    real_CreateDXGIFactory = (void *)GetProcAddress(h, "CreateDXGIFactory"); if (!real_CreateDXGIFactory) missing++;
    real_CreateDXGIFactory1 = (void *)GetProcAddress(h, "CreateDXGIFactory1"); if (!real_CreateDXGIFactory1) missing++;
    real_CreateDXGIFactory2 = (void *)GetProcAddress(h, "CreateDXGIFactory2"); if (!real_CreateDXGIFactory2) missing++;
    real_DXGID3D10CreateDevice = (void *)GetProcAddress(h, "DXGID3D10CreateDevice"); if (!real_DXGID3D10CreateDevice) missing++;
    real_DXGID3D10CreateLayeredDevice = (void *)GetProcAddress(h, "DXGID3D10CreateLayeredDevice"); if (!real_DXGID3D10CreateLayeredDevice) missing++;
    real_DXGID3D10GetLayeredDeviceSize = (void *)GetProcAddress(h, "DXGID3D10GetLayeredDeviceSize"); if (!real_DXGID3D10GetLayeredDeviceSize) missing++;
    real_DXGID3D10RegisterLayers = (void *)GetProcAddress(h, "DXGID3D10RegisterLayers"); if (!real_DXGID3D10RegisterLayers) missing++;
    real_DXGIDeclareAdapterRemovalSupport = (void *)GetProcAddress(h, "DXGIDeclareAdapterRemovalSupport"); if (!real_DXGIDeclareAdapterRemovalSupport) missing++;
    real_DXGIDisableVBlankVirtualization = (void *)GetProcAddress(h, "DXGIDisableVBlankVirtualization"); if (!real_DXGIDisableVBlankVirtualization) missing++;
    real_DXGIGetDebugInterface1 = (void *)GetProcAddress(h, "DXGIGetDebugInterface1"); if (!real_DXGIGetDebugInterface1) missing++;
    real_DXGIReportAdapterConfiguration = (void *)GetProcAddress(h, "DXGIReportAdapterConfiguration"); if (!real_DXGIReportAdapterConfiguration) missing++;
    return missing;
}
